app:
  datasource:
    jdbc-url: <insert host here>
    username: postgres
    password: <insert password here>
    pool-size: 30

spring:
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false