app:
  datasource:
    jdbc-url: jdbc:postgresql://<insert host here>:5432/covid_database
    username: postgres
    password: <insert password here>
    pool-size: 30

spring:
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
